src/main/java/aurora/dga/web/beans/JobBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aurora.dga.web.beans;

import javax.faces.bean.ManagedBean;

/**
 *
 * @author Luis Caamaño
 */

@ManagedBean(name = "job", eager = true)

public class JobBean {
    
}

src/main/java/aurora/dga/web/FuelBean.java
package aurora.dga.web;

import Navixy.NavixyAPICalls;
import static Navixy.NavixyAPICalls.*;
import Navixy.NavixyJsonResponse;
import Navixy.NavixyTrack;
import Navixy.NavixyTracker;
import Navixy.NavixyTrackerState;
import Navixy.NavixyUser;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;

@ManagedBean(name = "fuel", eager = true)
public class FuelBean {
    public FuelBean() {
        System.out.println("FuelBean instantiated");
    }
//    public String getMessage() throws NoSuchAlgorithmException, IOException {
//
//        NavixyJsonResponse user;
//        user = NavixyAPICalls.navixyAPILogin("test@DGA.com", "1234567");
//        // user = navixyAPILogin("rbeltre@a24.com.do", "Richard");
//        System.out.println("LOGIN USER HASH " + user.toString());
//        
//        return user.toString();
//    }
    
//        public ArrayList<NavixyTracker> getTrackers() throws NoSuchAlgorithmException, IOException {
//
//        NavixyJsonResponse user;
//        user = NavixyAPICalls.navixyAPILogin("test@DGA.com", "1234567");
//        // user = navixyAPILogin("rbeltre@a24.com.do", "Richard");
//        System.out.println("LOGIN USER HASH " + user.toString());
//        ArrayList<NavixyTracker> navixyTrackers = NavixyAPICalls.navixyGetTrackers(user.getHash());
//
//        return navixyTrackers;
//    }
        
//        public ArrayList<NavixyTrack> getTracks() throws NoSuchAlgorithmException, IOException {
//            
//            String dateFrom = "2018-10-18 03:39:44";
//            String dateTo = "2018-12-24 03:39:44";
//            
//
//        
//        NavixyJsonResponse user;
//        user = NavixyAPICalls.navixyAPILogin("test@DGA.com", "1234567");
//        // user = navixyAPILogin("rbeltre@a24.com.do", "Richard");
//        System.out.println("LOGIN USER HASH " + user.toString());
//        ArrayList<NavixyTracker> navixyTrackers = NavixyAPICalls.navixyGetTrackers(user.getHash());
//        NavixyTracker navixyTracker = navixyTrackers.get(0);
//        String trackerID = navixyTracker.getId();
//        
//        ArrayList<NavixyTrack> trackList = navixyGetTrackList(user.getHash(), trackerID, dateFrom, dateTo);
//
//        
//        
//       // ArrayList<NavixyTrack> navixyTracks = NavixyAPICalls.navixyGetTrackList(user.getHash(), );
//
//        return trackList;
//    }     
        
        
        
//    public String getOpen() {
//
//        System.out.println("################################################################");
//        System.out.println("###########################   CANDADO ##########################");
//        System.out.println("################################################################");
//        NavixyJsonResponse user = null;
//        try {
//            user = NavixyAPICalls.navixyAPILogin("test@DGA.com", "1234567");
//        } catch (NoSuchAlgorithmException ex) {
//            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        // user = navixyAPILogin("rbeltre@a24.com.do", "Richard");
//        System.out.println("LOGIN USER HASH " + user.toString());
//        ArrayList<NavixyTracker> navixyTrackers = null;
//        try {
//            navixyTrackers = navixyGetTrackers(user.getHash());
//        } catch (IOException ex) {
//            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        NavixyTracker navixyTracker = navixyTrackers.get(0);
//        String trackerID = navixyTracker.getId();
//        try {
//            NavixyJsonResponse ff = NavixyAPICalls.navixyElectronicLockOpenCommand(user.getHash(), trackerID, "888888");
//        } catch (Exception ex) {
//            return "failure";
//        }
//
//        
//        return "success";
//    }   
        
    
    
//    public String getFuelChartData(){
//                String userHash = "dd67bd83b7ccc3040b6c8e887d799369";
//                String trackerID = "366988";
//        
//                Map<String, Object> trackerSchedule;
//        trackerSchedule = NavixyAPICalls.navixyGetScheduleList(userHash, trackerID);
//                Map<String, Object> dataFuel = (Map<String, Object>)trackerSchedule.get("report");
//                ArrayList rdataFuel;
//                rdataFuel =  (ArrayList)dataFuel.get("sheets");
//                dataFuel = (Map<String, Object>) rdataFuel.get(0);
//                rdataFuel =  (ArrayList) dataFuel.get("sections");
//                dataFuel = (Map<String, Object>) rdataFuel.get(0);
//                rdataFuel =  (ArrayList) dataFuel.get("data_sets");
//                dataFuel = (Map<String, Object>) rdataFuel.get(0);
//                rdataFuel =  (ArrayList) dataFuel.get("points");
//                    System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&");
//                    System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&");
//                    System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&");
//                    System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&");
//                    return rdataFuel.toString();
//                
//        return "";
//        
//    }
    
    public ArrayList<NavixyTrackerState> getState() {
    //public NavixyTrackerState getState() {

        System.out.println("################################################################");
        System.out.println("###########################   STATE   ##########################");
        System.out.println("################################################################");
        
        NavixyUser navixyUser;
        
        ArrayList<NavixyTracker> navixyTrackers = null;
        NavixyTrackerState trackerState = null;

        try {
           Map<String, Object> user = NavixyAPICalls.navixyAPILogin("test@DGA.com", "1234567");
            
            navixyUser = new Gson().fromJson(user.toString(), new TypeToken<NavixyUser>() {
            }.getType());        
            
            navixyTrackers = listNavixyTrackers( navixyGetTrackers(navixyUser.getHash()));
        
            System.out.println("LOGIN USER HASH " + navixyUser.toString());
                        
            NavixyTracker navixyTracker = navixyTrackers.get(0);
            
            String trackerID = navixyTracker.getId();
            
            trackerState = (NavixyTrackerState)NavixyAPICalls.navixyTrackerGetState(navixyUser.getHash(), trackerID);


        
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        // user = navixyAPILogin("rbeltre@a24.com.do", "Richard");

        
            


        ArrayList<NavixyTrackerState> arrayList = new ArrayList<>();
        arrayList.add(trackerState);
        return arrayList;
        //return trackerState;
    }   
    
}

src/main/java/aurora/dga/web/FuelsBean.java
package aurora.dga.web;

import Navixy.NavixyAPICalls;
import static Navixy.NavixyAPICalls.*;
import Navixy.NavixyAPIFuelCalls;
import Navixy.NavixyJsonResponse;
import Navixy.NavixyTrack;
import Navixy.NavixyTracker;
import Navixy.NavixyTrackerState;
import Navixy.NavixyUser;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.lang.reflect.Array;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;

@ManagedBean(name = "fuels", eager = true)
public class FuelsBean {
    public FuelsBean() {
        System.out.println("FuelBean instantiated");
    }
    
    
private static <V, K> Map<V, K> invert(Map<K, V> map) {

    Map<V, K> inv = new HashMap<V, K>();

    for (Entry<K, V> entry : map.entrySet())
        inv.put(entry.getValue(), entry.getKey());

    return inv;
}
    
    public String getFuelChartData() throws IOException{
                String userHash = "dd67bd83b7ccc3040b6c8e887d799369";
                String trackerID = "366988";
        
                Map<String, Object> trackerSchedule;
                trackerSchedule = NavixyAPIFuelCalls. navixyGetScheduleList2(userHash, trackerID);
                Map<String, Object> dataFuel = (Map<String, Object>)trackerSchedule.get("report");
                ArrayList rdataFuel;
                rdataFuel =  (ArrayList)dataFuel.get("sheets");
                dataFuel = (Map<String, Object>) rdataFuel.get(0);
                rdataFuel =  (ArrayList) dataFuel.get("sections");
                dataFuel = (Map<String, Object>) rdataFuel.get(0);
                rdataFuel =  (ArrayList) dataFuel.get("data_sets");
                dataFuel = (Map<String, Object>) rdataFuel.get(0);
                //Map<String, Object> dataFuelInv= invert((Map<K, V>) dataFuel);
                
                rdataFuel =  (ArrayList) dataFuel.get("points");
                
                
                
                String ss="[";
                for(int i=0;i<rdataFuel.size();i++){
                    dataFuel=(Map<String, Object>) rdataFuel.get(i);
                    ss+="[";
                    ss+="dateFormatter.formatValue(new Date(";
                    Double dou = (Double)dataFuel.get("ts");
                    
                    Long lon = dou.longValue()*1000;
                    
                    ss+= lon;
                    ss+="))";
                    ss+=",\n";   ////////////////////////////
                    ss+=dataFuel.get("v");
                    ss+="]\n";
                    if (i<rdataFuel.size()-1) ss+=",";
                }
                ss+="]";
                
                
 
//                    ss = rdataFuel.toString();
//                    ss=ss.replace("{", "[");
//                    ss=ss.replace("}", "]");
//                    ss=ss.replace("ts=", "");
//                    ss=ss.replace("v=", "");
//                    ss=ss.replace("null", "0");
                    
                    System.out.println("SSS " + ss);
                    return ss ;
                
        
    }
    
    public ArrayList<NavixyTrackerState> getState() {
    //public NavixyTrackerState getState() {

        System.out.println("################################################################");
        System.out.println("###########################   STATE   ##########################");
        System.out.println("################################################################");
        
        NavixyUser navixyUser;

                ArrayList<NavixyTrackerState> arrayList = new ArrayList<>();
        try {
            
            
            Map<String, Object> user = NavixyAPICalls.navixyAPILogin("test@DGA.com", "1234567");
            
            navixyUser = new Gson().fromJson(user.toString(), new TypeToken<NavixyUser>() {
            }.getType());        
            
            System.out.println("LOGIN USER HASH " + navixyUser.toString());
            
            ArrayList<NavixyTracker> navixyTrackers = null;
            
            navixyTrackers = listNavixyTrackers( navixyGetTrackers(navixyUser.getHash()));
        NavixyTracker navixyTracker = navixyTrackers.get(0);
        String trackerID = navixyTracker.getId();
            
        NavixyTrackerState trackerState = null;
        
                    trackerState = (NavixyTrackerState)NavixyAPICalls.navixyTrackerGetState(navixyUser.getHash(), trackerID);
        arrayList.add(trackerState);

            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
        }

    




        return arrayList;
        //return trackerState;
    }   
    
}

src/main/java/aurora/dga/web/NavigationController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aurora.dga.web;

import java.io.Serializable;
import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;

/**
 *
 * @author Luis Caamaño
 */
@ManagedBean(name = "navigationController", eager = true)
@ViewScoped
@Dependent


public class NavigationController implements Serializable {
   @ManagedProperty(value = "#{param.passcode}")
   private String passcode;
    /**
     * Creates a new instance of NavigationController
     */
    
        public String pageChanger(){
            System.out.println("EEE##################\n"
                    + "passcode " + passcode);
            if(passcode.equals("aurora")) {
                return "pagina2";
            }
        return "error";
    }

    public String getPasscode() {
        return passcode;
    }

    public void setPasscode(String passcode) {
        this.passcode = passcode;
    }
}
    


src/main/java/aurora/dga/web/WelcomeBean.java
package aurora.dga.web;

import Navixy.NavixyAPICalls;
import static Navixy.NavixyAPICalls.listNavixyTrackers;
import static Navixy.NavixyAPICalls.navixyGetTrackList;
import static Navixy.NavixyAPICalls.navixyGetTrackers;
import Navixy.NavixyJsonResponse;
import Navixy.NavixyTrack;
import Navixy.NavixyTracker;
import Navixy.NavixyUser;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;

@ManagedBean(name = "welcome", eager = true)
public class WelcomeBean {
    
    
    public ArrayList<NavixyTracker> navixyTrackers;
    public ArrayList<NavixyTrack> trackList;
    String dateFrom = "2018-10-18 03:39:44";
    String dateTo = "2018-12-24 03:39:44";
    //NavixyTracker navixyTracker;
    
    public WelcomeBean() {
        
        System.out.println("NEWWWW WelcomeBean instantiated");
        
        
        NavixyUser navixyUser;

        
        
        try {

            Map<String, Object> user = NavixyAPICalls.navixyAPILogin("test@DGA.com", "1234567");
            
            navixyUser = new Gson().fromJson(user.toString(), new TypeToken<NavixyUser>() {
            }.getType());        
            
            navixyTrackers = listNavixyTrackers( NavixyAPICalls.navixyGetTrackers(navixyUser.getHash()));
            NavixyTracker navixyTracker = navixyTrackers.get(0);
            String trackerID = navixyTracker.getId();
            trackList = navixyGetTrackList(navixyUser.getHash(), trackerID, dateFrom, dateTo);

            
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(WelcomeBean.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }
           
    public ArrayList<NavixyTracker> getTrackers(String trackerr) throws NoSuchAlgorithmException, IOException {
        return navixyTrackers;
    }
        
    public ArrayList<NavixyTrack> getTracks() throws NoSuchAlgorithmException, IOException {
        return trackList;
    }     
        
        
        
    public String getCandado() {

        System.out.println("################################################################");
        System.out.println("###########################   CANDADO ##########################");
        System.out.println("################################################################");

        NavixyTracker navixyTracker = navixyTrackers.get(0);
        String trackerID = navixyTracker.getId();
        try {
           // NavixyJsonResponse ff = NavixyAPICalls.navixyElectronicLockOpenCommand(user.getHash(), trackerID, "888888");
        } catch (Exception ex) {
            return "failure";
        }
        
        return "success";
    }   
        
}

src/main/webapp/fuel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        

    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

google.charts.load('current', {packages: ['corechart', 'line']});
google.charts.setOnLoadCallback(drawCurveTypes);

function drawCurveTypes() {
      var data = new google.visualization.DataTable(),
              dateFormatter = new google.visualization.DateFormat({formatType: 'short'});
      data.addColumn('string', 'ts');
      data.addColumn('number', 'v');
      //data.addColumn('number', 'Cats');
/*
     data.addRows([
        [0, 0],    [1, 10],   [2, 23],  [3, 17],   [4, 18],  [5, 9]
              ]);
*/
data.addRows(#{fuels.fuelChartData});

      var options = {
        hAxis: {
          title: 'Track Data'
        },
        vAxis: {
          title: 'Combustible'
        },
        series: {
          1: {curveType: 'function'}
        }
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
    </script>

  
    </h:head>
    <h:body>
        

            <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>

 
        
<h1>ESTATUS </h1>


<h:dataTable value="#{fuels.state}" var="o"
                                 styleClass="order-table"
                                 headerClass="order-table-header"
                                 rowClasses="order-table-odd-row,order-table-even-row"
                                 >

                        <h:column>
                            <!-- column header -->
                            <f:facet name="header">ID Interno de Dispositivo</f:facet>
                            <!-- row record -->
                            #{o.battery_level}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Etiqueta</f:facet>
                                #{o.gps}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Modelo</f:facet>
                                #{o.connection_status}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Es Candado Clonado?</f:facet>
                                #{o.actual_track_update}
                        </h:column>

                    </h:dataTable>
    </h:body>
</html>

src/main/webapp/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">Home</ui:define>

    <ui:define name="header">
        <meta name="description" content=""/>
        <meta property="og:description" content="" />
        <meta property="og:title" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
    </ui:define>

    <ui:define name="content">
        <!--		<h1>Home</h1>-->

        <!--		<h1>{welcome.message}</h1>-->
        <!--                <h1>Home</h1>-->

        <html xmlns="http://www.w3.org/1999/xhtml"   
              xmlns:h="http://java.sun.com/jsf/html"
              xmlns:f="http://java.sun.com/jsf/core"
              xmlns:ui="http://java.sun.com/jsf/facelets"
              >
            <h:head>
                <h:outputStylesheet library="css" name="table-style.css"  />
            </h:head>
            <h:body>
                <h:form>
                    <h1>Captura de Datos de Navixy</h1>

                    <h:dataTable value="#{welcome.trackers}" var="o"
                                 styleClass="order-table"
                                 headerClass="order-table-header"
                                 rowClasses="order-table-odd-row,order-table-even-row"
                                 >

                        <h:column>
                            <!-- column header -->
                            <f:facet name="header">ID Interno de Dispositivo</f:facet>
                            <!-- row record -->
                            #{o.id}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Etiqueta</f:facet>
                                #{o.label}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Modelo</f:facet>
                                #{o.source.model}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Es Candado Clonado?</f:facet>
                                #{o.clone}
                        </h:column>

                    </h:dataTable>


                    <h:dataTable value="#{welcome.tracks}" var="o"
                                 styleClass="order-table"
                                 headerClass="order-table-header"
                                 rowClasses="order-table-odd-row,order-table-even-row"
                                 >
                        <h:column>
                            <!-- column header -->
                            <f:facet name="header">Fecha de Inicio</f:facet>
                            <!-- row record -->
                            #{o.start_date}
                        </h:column>
                        <h:column>
                            <!-- column header -->
                            <f:facet name="header">Salida</f:facet>
                            <!-- row record -->
                            #{o.start_address}
                        </h:column>    			
                        <h:column>
                            <!-- column header -->
                            <f:facet name="header">Fecha de Fin</f:facet>
                            <!-- row record -->
                            #{o.end_date}
                        </h:column>  

                        <h:column>
                            <f:facet name="header">Llegada</f:facet>
                                #{o.end_address}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Velocidad Promedio    </f:facet>
                                #{o.avg_speed}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Longitud</f:facet>
                                #{o.length}
                        </h:column>

                    </h:dataTable>
                </h:form>
                <h:form>    
                    <br />
                    Pulse el siguiente boton para abrir el Candado
                    <!--        <button onclick="{candado.candado}">open</button>-->
                    <h:commandButton   value = "ABRETE SESAMO" action="#{candado.open}" />

                    <!--<h:link outcome = "user" value = "left" onclick="{welcome.candado}">Abrir</h:link>-->
                </h:form>
            </h:body>
        </html>

    </ui:define>
</ui:composition>

src/main/webapp/page1.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">Home</ui:define>

    <ui:define name="header">
        <meta name="description" content=""/>
        <meta property="og:description" content="" />
        <meta property="og:title" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
    </ui:define>

    <ui:define name="content">
        <!--		<h1>Home</h1>-->

        <!--		<h1>{welcome.message}</h1>-->
        <!--                <h1>Home</h1>-->

        <html xmlns="http://www.w3.org/1999/xhtml"   
              xmlns:h="http://java.sun.com/jsf/html"
              xmlns:f="http://java.sun.com/jsf/core"
              xmlns:ui="http://java.sun.com/jsf/facelets"
              >
            <h:head>
                <h:outputStylesheet library="css" name="table-style.css"  />
            </h:head>
            <h:body>
                <h:form>
                    <h1>ABIERTO</h1>
                    
                    Estado: <<#{candado.actividad}>>

                    <h:dataTable value="#{status.state}" var="s"
                                 styleClass="order-table"
                                 headerClass="order-table-header"
                                 rowClasses="order-table-odd-row,order-table-even-row"
                                 >

                        <h:column>
                            <!-- column header -->
                            <f:facet name="header">Nivel GSM</f:facet>
                            #{s.gsm.network_name }                            
                        </h:column>
                        <h:column>
                            <!-- column header -->
                            <f:facet name="header">Nivel GSM</f:facet>
                            #{s.gsm.signal_level}                            
                        </h:column>

                        <h:column>
                            <f:facet name="header">Señal GPS</f:facet>
                                #{s.gps.signal_level}
                        </h:column>

                    </h:dataTable>

                </h:form>

            </h:body>
        </html>

    </ui:define>
</ui:composition>

src/main/webapp/page2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>DGA - ReComTAC</title>
    </h:head>
    <h:body>
Cerrado        
Estado: <<#{candado.actividad}>>
    </h:body>
</html>

src/main/webapp/recomtac.xhtml
<!DOCTYPE html>
<html           xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>RECOMTAC</title>
        <meta charset="utf-8" />

        <script src="resources/script/app3.js"></script>

    </h:head>
    <h:body>

<!--        Container for map
        <div id="mapContainer"></div>
        <p id="demo">Change Me</p>
        <button type="button" onclick="myFunction()">Try Me</button>-->


        <h:form>
            <h:panelGrid>
                <h:outputLabel value="Login: " style="font-weight: bold" />
                <h:inputText value="#{UserBean.login}" 
                             required="false" 
                             requiredMessage="Error: Introduce el Login"  />
                <h:outputLabel value="Password: " style="font-weight: bold" />
                <h:inputSecret value="#{UserBean.password}" 
                               required="false"
                               requiredMessage="Error: Introduce el Password" />
                <h:commandButton id="submit" value="Loguear" action="respuesta" />
                <h:commandButton id="reset" value="Limpiar" type="reset" />
            </h:panelGrid>    
        </h:form>

    </h:body>
</html>

src/main/webapp/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      lang="no">
<f:view transient="true" contentType="text/html;charset=UTF-8">
    <h:head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
        <meta name="mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <title><ui:insert name="title">Title</ui:insert></title>
	<link rel="stylesheet" href="#{request.contextPath}/javax.faces.resource/app.css.xhtml?ln=style"/>
	<h:outputScript library="script" name="app.js"/>
        <ui:insert name="header"/>
    </h:head>

    <h:body>
		<div class="content">
			<ui:insert name="content"/>
		</div>
        <footer class="footer">
            <ui:insert name="footer"/>
        </footer>
    </h:body>
</f:view>
</html>